### ISSUE TITLE
Application run error

### ISSUE THREAD

**Issue by akikrahman** [hmcts/spring-boot-template#314]
### If this entry is related to a bug, please provide the steps to reproduce it

I ran the steps to build and run the application but find there is an error creating bean with name 'configurationPropertiesBeans' 

git clone https://github.com/hmcts/spring-boot-template.git
cd spring-boot-template folder 
./gradlew build
./gradlew assemble
docker-compose build
docker-compose up

see the following error as attached
[application-error.txt](https://github.com/hmcts/spring-boot-template/files/6879198/application-error.txt)

**Comment by timja** [comment]
You need to run the init script first @akikrahman https://github.com/hmcts/spring-boot-template#setup

**Comment by akikrahman** [comment]
Hi - I have run the init script and found the same error as before - I used the parameters: 3300, akik, prod, application.
[application-error2.txt](https://github.com/hmcts/spring-boot-template/files/6884567/application-error2.txt)

**Comment by timja** [comment]
can you try revert this PR locally:
https://github.com/hmcts/spring-boot-template/pull/313

It's probably related to
https://hmcts-reform.slack.com/archives/C6DN09J8G/p1627291578118100

**Comment by Sparkeroo96** [comment]
I reverted to this PR: e5dd04592e520ed5d0ef51d53383b6a964667b79

Ran with the steps above including the init script.

I have the same issue with configurationpropertiesbean when it comes to running the container
[docker-fail.txt](https://github.com/hmcts/spring-boot-template/files/6884961/docker-fail.txt)


I'm not sure if the init.sh is working properly though, I am running it on a windows device (WSL is enabled) could this be an issue?

**Comment by akikrahman** [comment]
I've tried going back to commit 4d4ad0e757edcc713df6213e269df381f026e495 and still get the same error. I'm running in Ubuntu 18.04 and scripts seem to run without any errors. There is still an issue with " Error creating bean with name 'configurationPropertiesBeans' defined in class path resource [org/springframework/cloud/autoconfigure/ConfigurationPropertiesRebinderAutoConfiguration.class]".

**Comment by akikrahman** [comment]
I have got the template to run by making the following changes:
commented out lines 5 and 8 in application.java (removing the circuitbreaker code)
commented out lines 190, 195 and 196 (removing spring cloud and some embedded tomcat dependencies)

Then the build instructions worked.

**Comment by Sparkeroo96** [comment]
@timja I have just tested this on a Mac device now and still get the errors above when running locally.
It again works with the removal of these lines however they must be there for a reason and removing them is probably less than ideal.

Is there any plan to resolve this or is the idea to remove these lines going forward?

**Comment by timja** [comment]
hystrix needs to be removed and the tomcat ones are probably there to keep dependency check happy if spring boot is up to date enough then they can be removed.

any PRs are welcomed
