### ISSUE TITLE
Init script isn't compatible with gnu sed

### ISSUE THREAD

**Issue by timja** [hmcts/spring-boot-template#58]
### What would you like to change?
Make it work on gnu sed and bsd sed, pain in the butt though

### How do you think that would improve the project?
Anyone who has gnu sed installed / isn't on mac will be able to use this

### If this entry is related to a bug, please provide the steps to reproduce it
on mac run:
```
brew install gnu-sed
brew link gnu-sed  (i think) or alias sed=gnu-sed
```

Run the init script
```
$ sed -i '' '1s/.*/# hi-hi/' README.md
sed: can't read 1s/.*/# hi-hi/: No such file or directory
```

I tried doing this:
https://stackoverflow.com/a/14813278/4951015

If you remove the spaces it will work with gnu-sed but then it doesn't work with mac 
:(

**Comment by doncem** [comment]
@timja can this be closed now?
